plugins:
  - rubocop-performance

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/fixtures/**/*'

# Disable problematic cops
RSpec/FactoryBot:
  Enabled: false

FactoryBot/CreateList:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 120

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# RSpec
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/MessageSpies:
  EnforcedStyle: receive 